### ISSUE TITLE
Einheiten hinzufügen

### ISSUE THREAD

**Issue by Mart-Muc** [ixs/tasmota-sml-parser#1]
Hi Andreas,
a: ist es mit dem sml script möglich, gleich die Einheiten für MQTT hinzuzufügen, dass ich das nicht in Home Assistent machen muss?

b: gibt es ein decodierung der hex seriennummer in decimal?

Danke, Mart

**Comment by ixs** [comment]
Hi @Mart-Muc,

Das sollte mit dem SML Script möglich sein.
Das Script versucht dies ja bereits, aber wenn es nicht klappt, dann gibt es halt Daten ohne Einheiten:
https://github.com/ixs/tasmota-sml-parser/blob/master/sml_decoder.py#L82-L96

Die SML Language Defintion für Tasmota ist bei [https://tasmota.github.io/docs/Smart-Meter-Interface/#meter-definition 
](https://tasmota.github.io/docs/Smart-Meter-Interface/#meter-definition) einsehbar. UoM ist das Stichwort.

Die Seriennummer kann eventuell auch über die Meter Metrics modifiziert werden, musst mal mit den `decoder` Werten rumspielen.

Viel Glück. Ich mache das Ticket mal zu, falls noch was ist, kannste ja nochmal aufmachen.
