### ISSUE TITLE
Interpretation weiterer SML codes (hier: Apator Norax 3D)

### ISSUE THREAD

**Issue by kongo09** [ixs/tasmota-sml-parser#6]
Der Decoder lässt einige Codes als unbekannt ohne Dekodierung. Für das Apator Norax 3D habe ich zwei Beispiele, die ggf. ergänzt werden könnten - vielleicht bewegen sie sich aber auch außerhalb des offiziellen SML Standard.

Beispiel SML | OBIS | Bedeutung | Dekodierung | Erläuterung
----|------|------------|------------|-----
`77 07 01 00 60 32 01 01 01 01 01 01 04 41 50 41 01 `  | `1.0.96.50.1.1` | Identifizierung des Herstellers | APA | entspricht den ASCII Werten von `41` `50` `41`
`77 07 01 00 60 01 00 ff 01 01 01 01 0b 0a 01 41 50 41 01 05 b9 e3 74 01 ` | `1.0.96.1.0.255` | Identifizierung des Geräts gem. der Norm DIN 43863-5 | 1 APA 01 96068468 

Quellen:
- [OBIS Codes des Apator Norax 3D](https://www.rng.de/bedienungsanleitung-apator-norax3d.pdfx)
- [DIN 43863-5](https://netze.estw.de/erlangenGips/Erlangen/__attic__20210120_155237__estw1.de/Kopfnavigation/Netze/Messwesen/Messwesen/Herstelleruebergreifende-Identifikationsnummer-fuer-Messeinrichtungen.pdf)
- eigene Auslesung

Die Zählernummer scheint mir schwierig, weil diese noch nach DIN 43863-5 dekodiert ist:

HEX | Decodierung | Klartext
----|------|-----
`01` | Integer | 1
`41` `50` `41` | ASCII | APA
`01` | HEX | 01
`05` `b9` `e3` `74` | Integer | 96068468

Wie das mit Tasmota interpretiert werden kann, erschließt sich mir leider nicht.

**Comment by ixs** [comment]
Der Tasmota Parser selber liest kein SML und dekodiert keine Namen.
Stattdessen wird die libsml Library dafür benutzt. Die dort hinterlegten Namen sind in https://github.com/spacemanspiff2007/SmlLib/blob/master/src/smllib/const.py ersichtlich.

Die OBIS Tabelle muss also dort erweitert werden.
